- name: Install Pods
  run: |
    cd QVGrab
    pod install --repo-update

- name: Debug workspace
  run: |
    find . -name "*.xcworkspace"

- name: Build Archive
  run: |
    WORKSPACE=$(find . -name "*.xcworkspace" | head -n 1)

    echo "Using workspace: $WORKSPACE"

    xcodebuild archive \
      -workspace "$WORKSPACE" \
      -scheme QVGrab \
      -sdk iphoneos \
      -configuration Release \
      -archivePath build/QVGrab.xcarchive \
      CODE_SIGNING_ALLOWED=NO